trigger: none        # no se ejecuta por push (solo cron o manual)
pr: none

schedules:
  - cron: "0 6 * * *"     # 06:00 UTC ≈ 08:00 Europe/Madrid en verano
    displayName: Daily Ingestion
    always: true
    branches:
      include:
        - main

variables:
  PYTHON_VERSION: '3.11'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(PYTHON_VERSION)'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: Install dependencies

  # Tests rápidos (opcional pero recomendable)
  - script: |
      python -m pytest -q
    displayName: Run tests

  # Ejecuta el pipeline de ingesta
  - script: |
      python cli_ingest.py
    displayName: Run ingestion
    env:
      DATABASE_URL: $(DATABASE_URL)
      NEWSAPI_KEY:  $(NEWSAPI_KEY)
      DAYS_BACK: "7"
      PAGE_SIZE: "100"
      MAX_PAGES: "1"
