name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run:
    runs-on: ubuntu-24.04
    env:
      # Inyecta aquí los secrets
      NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      ENABLE_SCHEDULER: "false"     # en CI normalmente mejor desactivar
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m pytest -q
